inicio/urls.py
from django.urls import path
from inicio import views

app_name ='inicio'

urlpatterns = [
    path('',views.inicio, name='inicio'),
    path('acerca_de_mi/', views.acerca_de_mi, name='acerca_de_mi'),
    
     
    
    path('crear_autos/', views.CrearAuto.as_view(), name='crear_autos'),
    path('buscar/', views.BuscarAuto.as_view(), name='buscar_autos'),
    path('eliminar/<int:pk>/', views.EliminarAuto.as_view(), name='eliminar_autos'),
    path('modificar_auto/<int:pk>/', views.ModificarAuto.as_view(), name='modificar_autos'),
    path('mostrar_auto/<int:pk>/', views.MostrarAuto.as_view(), name='mostrar_autos'),
]

miprimerdjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name = 'usuario'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name='logout'),
    path('registro/', views.registrarse, name='registrarse'),
    path('perfil/editar/', views.edicion_perfil, name='editar_perfil'),
    path('perfil/editar/password/', views.ModificarPass.as_view(), name='modificar_pass')
    ]

inicio/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Auto(models.Model):
    marca = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)
    anio = models.IntegerField()
    descripcion = RichTextField(null= True)
    imagen = models.ImageField( upload_to="autos", null=True , blank=True )

    def __str__(self):
        return f"{self.marca} {self.modelo} ({self.anio})"

usuario/models.py
from django.db import models
from django.contrib.auth.models import User



class InfoExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)

inicio/forms.py
from django import forms
from ckeditor.fields import RichTextFormField
class AutoFormPadre(forms.Form):
    marca = forms.CharField(max_length=100)
    modelo = forms.CharField(max_length=100)
    anio = forms.IntegerField()
    descripcion = RichTextFormField()
    imagen=forms.ImageField()
    
class AutoForm(AutoFormPadre):
    ...

class ModificarAutoForm(AutoFormPadre):
    ...    

class BuscarAuto(forms.Form):
    marca= forms.CharField(max_length=100, required= False)

inicio/views.py
from django.db.models.query import QuerySet
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.template import loader
from django.shortcuts import render, redirect
from django.urls import reverse
from inicio.forms import AutoForm, BuscarAuto, ModificarAutoForm
from inicio.models import Auto
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
def inicio (request):
    return render(request,'inicio/inicio.html')

def acerca_de_mi (request):
    return render(request,'inicio/acerca_de_mi.html')

    
class CrearAuto(LoginRequiredMixin,CreateView):
   model = Auto
   template_name = 'inicio/CBV/crear_autos_CBV.html'
   fields = ['marca', 'modelo', 'anio','descripcion','imagen']
   success_url = reverse_lazy('inicio:buscar_autos')
   
class BuscarAuto (ListView):
    model = Auto
    template_name = "inicio/CBV/buscar_autos_CBV.html"
    context_object_name = 'autos'
    
    

class ModificarAuto(LoginRequiredMixin, UpdateView):
    model = Auto
    template_name = "inicio/CBV/modificar_autos_CBV.html"
    fields = ['marca', 'modelo', 'anio','descripcion', 'imagen']
    success_url = reverse_lazy('inicio:buscar_autos')

class EliminarAuto(LoginRequiredMixin,DeleteView):
    model = Auto
    template_name = "inicio/CBV/eliminar_autos_CBV.html"
    success_url = reverse_lazy('inicio:buscar_autos')

class MostrarAuto(LoginRequiredMixin,DetailView):
    model = Auto
    template_name = "inicio/CBV/mostrar_autos_CBV.html"
  

usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login as django_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from usuario.form import MiFormularioDeCreacionDeUsuarios, MiFormularioDeEdicionDeDatosDeUsuario
from django.urls import reverse_lazy
from usuario.models import InfoExtra


# Create your views here.

def login(request):
    
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data['username']
            contrasenia = formulario.cleaned_data['password']
            
            user = authenticate(username=usuario, password=contrasenia)
            
            django_login(request, user)
            
            InfoExtra.objects.get_or_create(user=user)
            
            return redirect('inicio:inicio')
        else:
            return render(request, 'usuario/login.html',  {'formulario': formulario})
            
    formulario = AuthenticationForm()
    return render(request, 'usuario/login.html',  {'formulario': formulario})

def registrarse(request):
    
    if request.method == 'POST':
        formulario = MiFormularioDeCreacionDeUsuarios(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('usuario:login')
        else:
            return render(request, 'usuario/registro.html', {'formulario': formulario})
            
    formulario = MiFormularioDeCreacionDeUsuarios()
    return render(request, 'usuario/registro.html', {'formulario': formulario})

@login_required
def edicion_perfil(request):
    info_extra_user = request.user.infoextra
    if request.method == 'POST':
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(request.POST, request.FILES, instance=request.user)
        if formulario.is_valid():
            
            avatar = formulario.cleaned_data.get('avatar')
            if avatar:
                info_extra_user.avatar = avatar
                info_extra_user.save()
            
            formulario.save()
            return redirect('inicio:inicio')
    else:
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(initial={'avatar': info_extra_user.avatar}, instance=request.user)
        
    return render(request, 'usuario/edicion_perfil.html', {'formulario': formulario})

class ModificarPass(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuario/modificar_pass.html'
    success_url = reverse_lazy('usuario:editar_perfil')

inicio/templates/inicio/CBV/buscar_autos_CBV.html
{% extends 'base.html' %}
{% block titulo %}
<title>Buscar auto</title>
{% endblock titulo %}
<body>
  {% block h1_header %} 
  <h1>Listar Autos</h1>
  {% endblock h1_header %}
  
   {% block contenido %}
   
   <button>
    <a class="navbar-brand" href={% url 'inicio:crear_autos' %}>Crear auto</a>
   </button>
   
   
  {% if autos %}
  {% for auto in autos %}
  <li>
    {{auto}}
    <button class = "btn btn-primary">
        <a class="navbar-brand" href={%url 'inicio:mostrar_autos' auto.id%}>Ver mas</a>
    </button>
    --
    <button class = "btn btn-warning">
        <a class="navbar-brand" href={%url 'inicio:modificar_autos' auto.id%}>Modificar</a>
    </button>
    --
    <button class = "btn btn-danger">
        <a class="navbar-brand" href={%url 'inicio:eliminar_autos' auto.id%}>Eliminar</a>
    </button>
    
  </li>
  {% endfor %}
  {% else %}
  <p>No se encontraron resultados.</p>
  {% endif %}
  {% endblock contenido %}

</body>
</html>

inicio/templates/inicio/CBV/crear_autos_CBV.html
{% extends 'base.html' %}
<html>
<head>
  {% block titulo %}
    <title>Crear autos</title>
    {% endblock titulo %}
</head>
<body>
  {% block h1_header %}
  <h1>Crear Auto</h1>
  {% endblock h1_header %}
  
    {% block contenido %}
    <form action={% url 'inicio:crear_autos' %} method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      <table>
      {{form}}
      {{form.media}}
    </table>
      <button>Crear</button>
    </form>
    {% endblock contenido %}


</body>
</html>

inicio/templates/inicio/CBV/eliminar_autos_CBV.html
{% extends 'base.html' %}
<html>
<head>
  {% block titulo %}
    <title>Eliminar autos</title>
    {% endblock titulo %}
</head>
<body>
  {% block h1_header %}
  <h1>Eliminar Auto</h1>
  {% endblock h1_header %}
  
    {% block contenido %}
    <form action={% url 'inicio:eliminar_autos' auto.id %} method="post">
      {% csrf_token %}
     <p>Desea confirmar la eliminacion de {{auto}}</p>
      <button>Confirmar</button>
    </form>
    {% endblock contenido %}


</body>
</html>

inicio/templates/inicio/CBV/modificar_autos_CBV.html
{% extends 'base.html' %}
<html>
<head>
  {% block titulo %}
    <title>Modificar autos</title>
    {% endblock titulo %}
</head>
<body>
  {% block h1_header %}
  <h1>Modificar Auto</h1>
  {% endblock h1_header %}
  
    {% block contenido %}
    <form action={% url 'inicio:modificar_autos' auto.id %} method="POST" enctype='multipart/form-data'>
      {% csrf_token %}
      <table>
      {{form}}
      {{form.media}}
    </table>
      <button>Modificar</button>
    </form>
    {% endblock contenido %}


</body>
</html>

inicio/templates/inicio/CBV/mostrar_autos_CBV.html
{% extends 'base.html' %}
<html>
<head>
  {% block titulo %}
    <title> auto</title>
    {% endblock titulo %}
</head>
<body>
  {% block h1_header %}
  <h1>{{auto.marca}}</h1>
  {% endblock h1_header %}
  
    {% block contenido %}
   
     <li>modelo: {{auto.modelo}}</li>
     <li>año : {{auto.anio}}</li>
     <li>descripcion : {{auto.descripcion |safe}}</li>
     {% if auto.imagen %}
     <li>imagen: <img src={{auto.imagen.url}} alt="imagen del auto"></li>
     {% endif %}
    {% endblock contenido %}


</body>
</html>

inicio/templates/inicio/acerca_de_mi.html
{% extends 'base.html' %}

        {% block titulo %}
        <title>Acerca de mi</title>
        {% endblock titulo %}
        
     {% block h1_header %}
     <h1 class="mb-5">Acerca de mi</h1>
     {% endblock h1_header %}

     {% block contenido %}
     <p>Mi nombre es Lucas Trivisonno, tengo 19 años , me anote en el curso de python para poder extender mis conocimientos sobre el mundo de la programacion.
        Ademas hice el curso de frontend el cual me facilito para el uso de django que se usa el html . Hice este proyecto de python sobre crear tu propio auto ya que me fascinan los autos. 
    Mi obvetivo profesional es formar parte de un grupo de trabajo lider y exitoso , donde pueda desarrollar todos mis conocimientos . Trabajar en una empresa donde mi desempeño profesional sea valorado y que se me brinden oportunidades para crecer y capacitacion para ayudarme a mejorar. .</p>
     {% endblock contenido %}

inicio/templates/inicio/buscar.html
{% extends 'base.html' %}

<body>
  {% block h1_header %} 
  <h1>Buscar Autos</h1>
  {% endblock h1_header %}
  
   {% block contenido %}
   
   <button>
    <a class="navbar-brand" href={% url 'inicio:crear_autos' %}>Crear auto</a>
  </button>
   
   <form method="get">
    {{ formulario }}
    <button >Buscar</button>
  </form>
  {% if autos %}
  {% for auto in autos %}
  <li>{{auto}}</li>
  {% endfor %}
  {% else %}
  <p>No se encontraron resultados.</p>
  {% endif %}
  {% endblock contenido %}

</body>
</html>

inicio/templates/inicio/crear_autos.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html>
<head>
  {% block titulo %}
    <title>Crear autos</title>
    {% endblock titulo %}
</head>
<body>
  {% block h1_header %}
  <h1>Crear Auto</h1>
  {% endblock h1_header %}
  
    {% block contenido %}
    <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ formulario }}
    </table>
      <button>Crear</button>
    </form>
    {% endblock contenido %}


</body>
</html>

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}

        {% block titulo %}
        <title>Inicio</title>
        {% endblock titulo %}
        
     {% block h1_header %}
     <h1 class="mb-5">inicio</h1>
     {% endblock h1_header %}

     {% block contenido %}
     
     {% endblock contenido %}
                            
                            
                           

inicio/templates/inicio/modificar_auto.html
{% extends 'base.html' %}
<html>
<head>
  {% block titulo  %}
    <title>Modificar autos</title>
    {% endblock titulo %}
</head>
<body>
  {% block h1_header %}
  <h1>Modificar Auto</h1>
  {% endblock h1_header %}
  
    {% block contenido %}
    <form action="" method="POST">
      {% csrf_token %}
      <table>
      {{ formulario }}
    </table>
      <button>Modificar</button>
    </form>
    {% endblock contenido %}


</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block titulo %}
        <title>Landing Page - Start Bootstrap Theme</title>
        {% endblock titulo %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
       
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>inicio</a>
                <a class="navbar-brand" href={% url 'inicio:crear_autos' %}>Crear autos</a>
                <a class="navbar-brand" href={% url 'inicio:buscar_autos' %}>Listar autos</a>
                {% if request.user.is_authenticated %}
                {% if request.user.infoextra.avatar %}
                <img src={{request.user.infoextra.avatar.url}} alt="" height='45px'>
                {% endif %}
                <a class="navbar-brand" href={% url 'usuario:editar_perfil' %}>{{request.user.username}}</a>
                <a class="btn btn-secondary" href={% url 'usuario:logout' %}>Logout</a>
                {% else %}
                <a class="btn btn-primary" href={% url 'usuario:login' %}>Login</a>
                <a class="btn btn-primary" href={% url 'usuario:registrarse' %}>Registrarse</a>
                {% endif %}
            </div>
        </nav>
        
        <!-- Masthead-->
        
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            {% block h1_header %}
                            <h1 class="mb-5">Bienvenido a mi sitio web</h1>
                            {% endblock h1_header %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        
        <!-- Icons Grid-->
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><button><a class="navbar-brand" href={% url 'inicio:acerca_de_mi' %}>Acerca de mi</a></button></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

usuario/templates/usuario/edicion_perfil.html
{% extends 'base.html' %}

{% block titulo %}
<title>Edicion perfil</title>
{% endblock titulo %}

{% block h1_header %}
<h1>Editar perfil</h1> 
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:editar_perfil' %} method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Guardar cambios</button>
    <button type='button'><a class="navbar-brand" href={% url 'usuario:modificar_pass' %}>Cambiar contrasenia</a></button>
</form>
{% endblock contenido %}

usuario/templates/usuario/login.html
{% extends 'base.html' %}
<html>
<head>
    {% block titulo %}
    <title>Login</title>
    {% endblock titulo %}
</head>
<body>
  {% block h1_header %}
  <h1>Login</h1>
  {% endblock h1_header %}
  
    {% block contenido %}
    <form action={% url 'usuario:login' %} method="post">
      {% csrf_token %}
      <table>
      {{ formulario }}
    </table>
      <button>Login</button>
    </form>
    {% endblock contenido %}


</body>
</html>

usuario/templates/usuario/logout.html
{% extends 'base.html' %}
<html>
<head>
    {% block titulo %}
    <title>Logout</title>
    {% endblock titulo %}
</head>
<body>
  {% block h1_header %}
  <h1>Vuelve a loguearte para poder crear tu auto</h1>
  {% endblock h1_header %}
  
    {% block contenido %}
    
    {% endblock contenido %}


</body>
</html>

usuario/templates/usuario/modificar_pass.html
{% extends 'base.html' %}

{% block titulo %}
<title>Modificar pass</title>
{% endblock titulo %}

{% block h1_header %}
 <h1>Modificar password</h1>
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:modificar_pass' %} method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}

usuario/templates/usuario/registro.html
{% extends 'base.html' %}
<html>
<head>
    {% block titulo %}
    <title>Registro</title>
    {% endblock titulo %}
</head>
<body>
  {% block h1_header %}
  <h1>Registrate</h1>
  {% endblock h1_header %}
  
    {% block contenido %}
    <form action={% url 'usuario:registrarse' %} method="post">
      {% csrf_token %}
      <table>
      {{ formulario }}
    </table>
      <button>Crear cuenta</button>
    </form>
    {% endblock contenido %}


</body>
</html>